language: node_js
node_js:
  - "12"
notifications:
  email: false
cache: yarn
script: yarn test
jobs:
  include:
    - stage: npm release
      script: yarn build
      node_js: "12"
      deploy:
      - provider: npm
        skip_cleanup: true
        email: tminier01@gmail.com
        api_key: $NPM_KEY
        on:
          tags: true
